### ISSUE TITLE
DT client doesn't throw error for a missing 'end if' statement

### ISSUE THREAD

**Issue by dricard** [skirwan/clan-lord-client-issues#154]
Confirmed that missing the whole `end if` statement isn't really a problem...

**Comment by skirwan** [comment]
As of A38 omitting `end if` should _work_ like in the DT client, but still print warnings.

(Right now warnings look a lot more dire than they ought to: #158 )

I made the choice to show warnings for this situation because it's very possibly a latent bug.  Right now it's annoying because we have a lot of communal macro files with this kind of wrong-but-it-works situation, but from a future-looking POV I think this is the right call.

Mind looking at what your macros do in A38 and seeing if this is working like I intend?

**Comment by dricard** [comment]
I tested in a made up macro since it's easier to predict what's going to happen, It behaves the same in both clients. So it's all good. It's a bit strange (to me) that the behaviour is different if there is an else statement or not. With an else statement (and a missing end if) the execution continues, without an else statement (and a missing end if) the execution stops. Not sure why exactly, but both clients do the same thing.
I really like the new error message ("The if block starting on line 10 doesn\'t have an ending."), very useful. 👍

**Comment by dricard** [comment]
Forgot to close
