### ISSUE TITLE
Inventory window fails to load

### ISSUE THREAD

**Issue by spkzest** [skirwan/clan-lord-client-issues#225]
Almost certainly a bug in the code parsing inventory segments of the UDP packets.

**Comment by skirwan** [comment]
Okay, after a *lot* of testing and trying various things, I'm starting to think this is a server bug.

If the very first UDP packet of the play session is lost, the client has no way to request a replay of that sequence number.  The server will eventually resend data because it never got acknowledged... except for inventory data, which seems to get lost in the shuffle.

Gonna need to poke ServerGM about this one.
